### ISSUE TITLE
Access Keys does not work!

### ISSUE THREAD

**Issue by ParoTheParrot** [abego/YourSearchPlugin#2]
Is it possible to choose other access keys? 
See: http://tiddlywiki.abego-software.de/#[[YourSearch%20Help]]

**Comment by abego** [comment]
Please give some more details, like what operating system (incl version) and browser (+ version) you are using and what access keys are not working.

Also note that depending on your operating system or browser you may need to press different modifier key for the access keys. E.g. on Mac you need to press [Control][Alt] instead of just [Alt], and Firefox user need to press [Shift][Alt] instead of [Alt].

**Comment by abego** [comment]
No additional information provided to reproduce the issue after waiting for a month.
